#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'lib/fyt'

case ARGV.first
when 'run'
  unless DATA.flock(File::LOCK_NB | File::LOCK_EX)
    raise 'FYT already running ... exiting'
  end

  FYT.run
when 'config'
  FYT.config
when 'add'
  FYT.add
else
  puts "unknown paramter #{ARGV.first}"
end

__END__
DO NOT REMOVE: required for the DATA object above.
